### PR TITLE
Remove always-true if in field_for_schema()

### PR DESCRIPTION
**Pull request by altendky**
From what I can tell this condition can only be true if the calling code
doubly accessses internal things such as:

```python3
attr.ib(default=1, metadata={desert._make._DESERT_SENTINEL:{'required': True}})
```

### CODE REVIEW

**Comment by python-desert** [comment]
It seems at least possible that someone would want to require the value be present when taking it from json but not from Python. Is that what we think this means?:

```py
attr.ib(default=1, metadata={desert._make._DESERT_SENTINEL:{'required': True}})
```

**Comment by altendky** [comment]
Maybe? Maybe I missed a way to set it. I assumed the code was a remnant but I didn't dig into history etc.  Perhaps there should be a plan for the interface?  Presumably not an overhaul but something that would end up stating the solution to your scenario (if allowed).

**Comment by altendky** [comment]
Do we need to start a discussion back up here?  Either about acceptance or about leaving this to fall out in a later refactor.  no matter

**Comment by python-desert** [comment]
Opened an issue https://github.com/python-desert/desert/issues/76 to discuss. In the meantime let's remove it.

**Review by ghost — APPROVED** [review]

**Pull request merged**
