### PR TITLE
Add linkcheck retries.

### PR DESCRIPTION
**Pull request by ghost**
Codecov.io failed the build on master here:

https://travis-ci.com/python-desert/desert/jobs/280127630#L379

----

#

### CODE REVIEW

**Comment by altendky** [comment]
Change looks fine to the sphinx-untrained eye.  Did you test it a bunch before and note an elimination of failures after?

**Comment by python-desert** [comment]
The failures are intermittent and the retries will only reduce them somewhat.

**Comment by altendky** [comment]
Sure.  I setup a quick test to see how many failures with and without.  Ran 50x each at the same time and without yielded one failure and with yielded zero failures.  Not particularly enough to judge off of alone.  But, I think I saw several cases where the with-retry was hanging on a codecov request which would suggest that maybe the retries did actually alleviate the issue.  Going to leave them both running more times for more data while I do other stuff.  Seems like the issue is maybe an always-present-probability-of-failure rather than a 'long'-downtimes-occasionally and so the retries are making a difference.

```python3
import subprocess

d = {'pass': 0, 'fail': 0}

for _ in range(500):
    try:
        subprocess.run(['tox', '-e', 'doc'], check=True)
    except subprocess.CalledProcessError:
        d['fail'] += 1
    else:
        d['pass'] += 1

print(d)
```

**Comment by altendky** [comment]
At 500x the 'with retry' had zero failures and the 'without retry' had 15 failures.  Not to mention, retries are nice even when there aren't known issues...

**Review by altendky — APPROVED** [review]

**Pull request merged**
