### PR TITLE
Only require dataclasses backport for Python < 3.7

### LINKED ISSUE #102: Do not require dataclasses on python 3.7+
Python3.7+ comes with the package `dataclasses` built in. Desert fails to install from our internal pypi mirror, as that does not mirror the `dataclasses` packet anymore.

It seems the entry in this file should be made conditional somehow:
https://github.com/python-desert/desert/blob/631de5f98d0f3edd3ecbab57100c5664a43bf3d5/requirements.in#L1-L4

### PR DESCRIPTION
**Pull request by altendky**
Fixes #102

### CODE REVIEW

**Comment by darthberen** [comment]
@altendky @python-desert can this be merged? this issue with dataclasses is breaking our build on python 3.7 and 3.8 as the pip version of dataclasses is getting used rather than the stdlib.

**Comment by altendky** [comment]
Kick CI for a fresh build.  @python-desert, I can't override the required review so it will take someone else's involvement.

**Review by ghost — APPROVED** [review]

**Comment by python-desert** [comment]
Approved

**Comment by darthberen** [comment]
Thanks @altendky! Much appreciated

**Comment by altendky** [comment]
Still need to get the release, but sure thing.

**Pull request merged**
