### PR TITLE
Fix deprecation warnings

### PR DESCRIPTION
**Pull request by leameow**
I was getting a few warning due to `default` and `missing` being removed in Marshmallow4.

### CODE REVIEW

**Comment by dmares01** [comment]
If this could be merged over that would be amazing. I am getting the same deprecation warnings

**Review by dmares01 — DISMISSED** [review]
This fixes the deprecation warning I receive from Marshmallow and all functionality has been maintained in my testing

**Comment by mmerickel** [comment]
Would love to see this get merged and released. It fixes https://github.com/python-desert/desert/issues/179.

**Comment by leameow** [comment]
Rebased!

**Comment by mmerickel** [comment]
The issue is with marshmallow and was fixed in [3.15](https://github.com/marshmallow-code/marshmallow/pull/1903/files). I see dev-requirements.txt and test-requirements.txt pinned to 3.13 so likely the pin should just be updated.

**Comment by leameow** [comment]
I updated the dependencies in requirements.txt (running pip-compile --upgrade ...)

**Comment by leameow** [comment]
Seems like many dependencies are not supporting python 3.6 anymore (Such as marshmallow 3.15...)

Any thought about dropping python 3.6 support?

**Comment by leameow** [comment]
Seems like there's more error about typing in test_make and the setup of fixture generator I'm not familiar with. I've spent more time than I care at that point. Anyone feel free to take over!

**Comment by leameow** [comment]
Actually, I might have something that goes green now.

**Comment by leameow** [comment]
Ok this is it. I had to run the lock command under linux...

**Comment by mmerickel** [comment]
Ha, was just pointing that out. Nice work @isra17!

**Comment by mmerickel** [comment]
https://github.com/python-desert/desert/blob/6c5c54e81094b8c3f6bd488c1797e3b237e5229d/setup.py#L79 will need to be removed

**Comment by leameow** [comment]
done

**Comment by leameow** [comment]
done!

**Pull request merged**
